module SpreeHubspot
  class Configuration < Spree::Preferences::Configuration
    preference :user_name, :string, default: "Hubspot SMTP Username"
    preference :password, :string, default: "Hubspot SMTP Password"
    preference :address, :string, default: "Hubspot SMTP Hostname"
    preference :port, :integer, default: "Hubspot SMTP Port"
    preference :hapikey, :string, default: "Hubspot API Key"

    preference :nwb_order_confirmation_email_id, :string, default: ""
    preference :he_order_confirmation_email_id, :string, default: ""
    preference :pwb_order_confirmation_email_id, :string, default: ""
    preference :pwbca_order_confirmation_email_id, :string, default: ""
    preference :pwbuk_order_confirmation_email_id, :string, default: ""
    preference :pwbeu_order_confirmation_email_id, :string, default: ""
    preference :pwbau_order_confirmation_email_id, :string, default: ""

    preference :nwb_order_shipped_email_id, :string, default: ""
    preference :he_order_shipped_email_id, :string, default: ""
    preference :pwb_order_shipped_email_id, :string, default: ""
    preference :pwbca_order_shipped_email_id, :string, default: ""
    preference :pwbuk_order_shipped_email_id, :string, default: ""
    preference :pwbeu_order_shipped_email_id, :string, default: ""
    preference :pwbau_order_shipped_email_id, :string, default: ""

    preference :nwb_order_canceled_email_id, :string, default: ""
    preference :he_order_canceled_email_id, :string, default: ""
    preference :pwb_order_canceled_email_id, :string, default: ""
    preference :pwbca_order_canceled_email_id, :string, default: ""
    preference :pwbuk_order_canceled_email_id, :string, default: ""
    preference :pwbeu_order_canceled_email_id, :string, default: ""
    preference :pwbau_order_canceled_email_id, :string, default: ""

    preference :nwb_out_of_stock_email_id, :string, default: ""
    preference :he_out_of_stock_email_id, :string, default: ""
    preference :pwb_out_of_stock_email_id, :string, default: ""
    preference :pwbca_out_of_stock_email_id, :string, default: ""
    preference :pwbuk_out_of_stock_email_id, :string, default: ""
    preference :pwbeu_out_of_stock_email_id, :string, default: ""
    preference :pwbau_out_of_stock_email_id, :string, default: ""

    preference :nwb_password_reset_email_id, :string, default: ""
    preference :he_password_reset_email_id, :string, default: ""
    preference :pwb_password_reset_email_id, :string, default: ""
    preference :pwbca_password_reset_email_id, :string, default: ""
    preference :pwbuk_password_reset_email_id, :string, default: ""
    preference :pwbau_password_reset_email_id, :string, default: ""
    preference :pwbeu_password_reset_email_id, :string, default: ""

    preference :com_rma_email_id, :string, default: ""
    preference :ca_rma_email_id, :string, default: ""
    preference :uk_rma_email_id, :string, default: ""
    preference :aus_rma_email_id, :string, default: ""
    preference :eu_rma_email_id, :string, default: ""

    preference :pwb_subscription_recieved_email_id, :string, default: ""
    preference :pwb_subscription_reactivated_email_id, :string, default: ""
    preference :pwb_subscription_order_reminder_email_id, :string, default: ""
    preference :pwb_subscription_out_of_stock_email_id, :string, default: ""
    preference :pwb_subscription_generic_issue_email_id, :string, default: ""
    preference :pwb_subscription_credit_card_expired_email_id, :string, default: ""
    preference :pwb_subscription_canceled_email_id, :string, default: ""

    preference :nwb_subscription_recieved_email_id, :string, default: ""
    preference :nwb_subscription_reactivated_email_id, :string, default: ""
    preference :nwb_subscription_order_reminder_email_id, :string, default: ""
    preference :nwb_subscription_out_of_stock_email_id, :string, default: ""
    preference :nwb_subscription_generic_issue_email_id, :string, default: ""
    preference :nwb_subscription_credit_card_expired_email_id, :string, default: ""
    preference :nwb_subscription_canceled_email_id, :string, default: ""

    preference :he_subscription_recieved_email_id, :string, default: ""
    preference :he_subscription_reactivated_email_id, :string, default: ""
    preference :he_subscription_order_reminder_email_id, :string, default: ""
    preference :he_subscription_out_of_stock_email_id, :string, default: ""
    preference :he_subscription_generic_issue_email_id, :string, default: ""
    preference :he_subscription_credit_card_expired_email_id, :string, default: ""
    preference :he_subscription_canceled_email_id, :string, default: ""

    preference :pwbca_subscription_recieved_email_id, :string, default: ""
    preference :pwbca_subscription_reactivated_email_id, :string, default: ""
    preference :pwbca_subscription_order_reminder_email_id, :string, default: ""
    preference :pwbca_subscription_out_of_stock_email_id, :string, default: ""
    preference :pwbca_subscription_generic_issue_email_id, :string, default: ""
    preference :pwbca_subscription_credit_card_expired_email_id, :string, default: ""
    preference :pwbca_subscription_canceled_email_id, :string, default: ""

    preference :pwbuk_subscription_recieved_email_id, :string, default: ""
    preference :pwbuk_subscription_reactivated_email_id, :string, default: ""
    preference :pwbuk_subscription_order_reminder_email_id, :string, default: ""
    preference :pwbuk_subscription_out_of_stock_email_id, :string, default: ""
    preference :pwbuk_subscription_generic_issue_email_id, :string, default: ""
    preference :pwbuk_subscription_credit_card_expired_email_id, :string, default: ""
    preference :pwbuk_subscription_canceled_email_id, :string, default: ""

    preference :pwbau_subscription_recieved_email_id, :string, default: ""
    preference :pwbau_subscription_reactivated_email_id, :string, default: ""
    preference :pwbau_subscription_order_reminder_email_id, :string, default: ""
    preference :pwbau_subscription_out_of_stock_email_id, :string, default: ""
    preference :pwbau_subscription_generic_issue_email_id, :string, default: ""
    preference :pwbau_subscription_credit_card_expired_email_id, :string, default: ""
    preference :pwbau_subscription_canceled_email_id, :string, default: ""

    preference :pwbeu_subscription_recieved_email_id, :string, default: ""
    preference :pwbeu_subscription_reactivated_email_id, :string, default: ""
    preference :pwbeu_subscription_order_reminder_email_id, :string, default: ""
    preference :pwbeu_subscription_out_of_stock_email_id, :string, default: ""
    preference :pwbeu_subscription_generic_issue_email_id, :string, default: ""
    preference :pwbeu_subscription_credit_card_expired_email_id, :string, default: ""
    preference :pwbeu_subscription_canceled_email_id, :string, default: ""
  end
end